[tool.briefcase]
project_name = "Arborist"
bundle = "app.arborist"
version = "0.1.0"
url = "https://arborist.app"
license.file = "LICENSE"
author = "Nicholas Warren"
author_email = "nicholas.warren@austin.utexas.edu"

[tool.briefcase.app.arborist]
formal_name = "Arborist"
description = "The cross-platform app for efficiently performing Bayesian causal inference and supervised learning tasks using tree-based models, including BCF, BART, and XBART."
long_description = """More details about the app should go here.
"""
sources = [
    "src/arborist",
]
test_sources = [
    "tests",
]

requires = [
    # "PySide6-Addons~=6.7",
    "matplotlib>=3.7",
    "numpy",
    "pandas",
    "pyarrow",
    "PySide6",
    "PySide6-Essentials~=6.7",
    "requests",
    "scikit-learn",
    "scipy",
    "stochtree",
]

test_requires = [
    "pytest",
]

[tool.briefcase.app.arborist.macOS]
universal_build = false
requires = [
    "std-nslog~=1.0.3",
]

[tool.briefcase.app.arborist.linux]
requires = [
]

[tool.briefcase.app.arborist.linux.system.debian]
system_requires = [
]

system_runtime_requires = [
    # Derived from https://doc.qt.io/qt-6/linux-requirements.html
    "libxext6",
    "libxrender1",
    "libx11-xcb1",
    "libxkbcommon-x11-0",
    "libxcb-image0",
    "libxcb-cursor0",
    "libxcb-shape0",
    "libxcb-randr0",
    "libxcb-xfixes0",
    "libxcb-sync1",
    "libxcb-icccm4",
    "libxcb-keysyms1",
    "libfontconfig1",
    "libsm6",
    "libice6",
    "libglib2.0-0",
    "libgl1",
    "libegl1",
    "libdbus-1-3",
]

[tool.briefcase.app.arborist.linux.system.rhel]
system_requires = [
]

system_runtime_requires = [
    "qt6-qtbase-gui",
]

[tool.briefcase.app.arborist.linux.system.suse]
system_requires = [
]

system_runtime_requires = [
    "libgthread-2_0-0",
    "libQt6Gui6",
]

[tool.briefcase.app.arborist.linux.system.arch]
system_requires = [
]

system_runtime_requires = [
    "qt6-base",
]

[tool.briefcase.app.arborist.linux.appimage]
manylinux = "manylinux_2_28"

system_requires = [
# ?? FIXME
]

linuxdeploy_plugins = [
]

[tool.briefcase.app.arborist.linux.flatpak]
flatpak_runtime = "org.kde.Platform"
flatpak_runtime_version = "6.7"
flatpak_sdk = "org.kde.Sdk"

[tool.briefcase.app.arborist.windows]
requires = [
]

# Mobile deployments
[tool.briefcase.app.arborist.iOS]
supported = false

[tool.briefcase.app.arborist.android]
supported = false

# Web deployments
[tool.briefcase.app.arborist.web]
supported = false

